from datetime import datetime, timezone
from typing import Optional, Dict, Any

from .schemas import CarePlanOption, PathwayDecision, PathwayRequest, PathwayResponse


def run_pathway(
    patient_id: str,
    request: Optional[PathwayRequest] = None,
) -> PathwayResponse:
    """
    Runs the Clinical Emergency Risk Model & CarePlan Agent.
    Evaluates:
      1. Patient EHR / MRN records (baseline clinical risk)
      2. LLM Extracted Intake Data (chief complaint, onset, pain scale, location)
      3. Red Flag Safety Answers (10 screening questions)
    Outputs:
      - Risk Score (0-100%)
      - Decision (NOT_AVOIDABLE -> ER / Immediate Intervention vs POTENTIALLY_AVOIDABLE)
      - CarePlan options generated by CarePlan Agent.
    """
    # 1. Extract inputs
    chief_complaint = (request.chief_complaint if request else None) or "Unspecified concern"
    symptom_onset = (request.symptom_onset if request else None) or "Unknown"
    pain_scale = (request.pain_scale if request else 0) or 0
    location = (request.location if request else None) or "General"
    red_flags = (request.red_flag_answers if request else {}) or {}

    # 2. Risk Calculation Algorithm (ML/Rule-based hybrid)
    base_score = 15.0  # Baseline risk for presenting patient

    # Pain scale weight (0 to 10)
    pain_score = (pain_scale / 10.0) * 30.0
    base_score += pain_score

    # Sudden / Acute onset weight
    if any(kw in symptom_onset.lower() for kw in ["sudden", "acute", "immediate", "hour", "hours", "min"]):
        base_score += 15.0

    # High-risk symptom keywords
    high_risk_kws = ["chest", "breath", "shortness", "headache", "bleeding", "faint", "stroke", "numbness"]
    if any(kw in chief_complaint.lower() or kw in location.lower() for kw in high_risk_kws):
        base_score += 20.0

    # Red Flag triggered weight
    red_flag_count = sum(1 for v in red_flags.values() if v is True)
    base_score += red_flag_count * 25.0

    # Clamp score to [5.0, 99.0]
    final_score = min(max(round(base_score, 1), 5.0), 99.0)

    # 3. Categorize Risk Level & Decision
    if final_score >= 70.0 or red_flag_count > 0:
        risk_level = "CRITICAL" if final_score >= 85.0 else "HIGH"
        decision = PathwayDecision.NOT_AVOIDABLE
        explanation = (
            f"Risk score of {final_score}% ({risk_level}). "
            f"Presenting symptoms ({chief_complaint}, pain scale {pain_scale}/10) "
            f"require immediate clinical evaluation at an Emergency Department or Urgent Center."
        )
    elif final_score >= 40.0:
        risk_level = "MODERATE"
        decision = PathwayDecision.POTENTIALLY_AVOIDABLE
        explanation = (
            f"Risk score of {final_score}% ({risk_level}). "
            f"Symptoms are manageable through same-day Urgent Care or Telehealth clinical consultation."
        )
    else:
        risk_level = "LOW"
        decision = PathwayDecision.POTENTIALLY_AVOIDABLE
        explanation = (
            f"Risk score of {final_score}% ({risk_level}). "
            f"Non-emergency presentation. Recommended for Primary Care (PCP) or Telehealth follow-up."
        )

    # 4. CarePlan Agent Generation
    care_plan: list[CarePlanOption] = []
    if decision == PathwayDecision.NOT_AVOIDABLE:
        care_plan.append(
            CarePlanOption(
                title="Immediate Emergency Department Evaluation",
                urgency="Immediate",
                description="High-severity presentation requiring emergency clinical assessment and diagnostic workup.",
                recommended_action="Proceed to the nearest Emergency Room or dial 911 if experiencing distress.",
            )
        )
        care_plan.append(
            CarePlanOption(
                title="Care Manager Notification",
                urgency="Immediate",
                description="Alert sent to the on-call Nurse Care Manager for post-triage tracking.",
                recommended_action="Care team will follow up via phone within 2 hours.",
            )
        )
    else:
        care_plan.append(
            CarePlanOption(
                title="Telehealth / Same-Day Urgent Care",
                urgency="Moderate" if risk_level == "MODERATE" else "Routine",
                description=f"Same-day evaluation for {chief_complaint} to prevent symptom progression.",
                recommended_action="Book a virtual consultation or visit an affiliated Urgent Care center within 24 hours.",
            )
        )
        care_plan.append(
            CarePlanOption(
                title="Outpatient Care Plan & Monitoring",
                urgency="Routine",
                description="Personalized symptom monitoring and medication review plan.",
                recommended_action="Follow up with primary care physician within 3-5 days.",
            )
        )

    raw_agent_output = {
        "patient_id": patient_id,
        "calculated_risk_score": final_score,
        "risk_level": risk_level,
        "decision": decision.value,
        "red_flags_active": red_flag_count,
        "intake_fields_used": {
            "chief_complaint": chief_complaint,
            "symptom_onset": symptom_onset,
            "pain_scale": pain_scale,
            "location": location,
        },
    }

    return PathwayResponse(
        patient_id=patient_id,
        risk_score=final_score,
        risk_level=risk_level,
        decision=decision,
        explanation=explanation,
        care_plan=care_plan,
        predicted_at=datetime.now(timezone.utc),
        raw_agent_output=raw_agent_output,
    )
